binary_sensor:
  - platform: analog_threshold
    id: ${ch1_cover_name}_closed
    sensor_id: ${ch1_cover_name}_current
    threshold: ${closed_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch2_cover_name}_closed
    sensor_id: ${ch2_cover_name}_current
    threshold: ${closed_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch3_cover_name}_closed
    sensor_id: ${ch3_cover_name}_current
    threshold: ${closed_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch4_cover_name}_closed
    sensor_id: ${ch4_cover_name}_current
    threshold: ${closed_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch5_cover_name}_closed
    sensor_id: ${ch5_cover_name}_current
    threshold: ${closed_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch6_cover_name}_closed
    sensor_id: ${ch6_cover_name}_current
    threshold: ${closed_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch7_cover_name}_closed
    sensor_id: ${ch7_cover_name}_current
    threshold: ${closed_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch8_cover_name}_closed
    sensor_id: ${ch8_cover_name}_current
    threshold: ${closed_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch1_cover_name}_opened
    sensor_id: ${ch1_cover_name}_current
    threshold: ${opened_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch2_cover_name}_opened
    sensor_id: ${ch2_cover_name}_current
    threshold: ${opened_current}
    internal: true
    filters:
      - delayed_on: 100ms
      
  - platform: analog_threshold
    id: ${ch3_cover_name}_opened
    sensor_id: ${ch3_cover_name}_current
    threshold: ${opened_current}
    internal: true
    filters:
      - delayed_on: 100ms
      
  - platform: analog_threshold
    id: ${ch4_cover_name}_opened
    sensor_id: ${ch4_cover_name}_current
    threshold: ${opened_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch5_cover_name}_opened
    sensor_id: ${ch5_cover_name}_current
    threshold: ${opened_current}
    internal: true
    filters:
      - delayed_on: 100ms

  - platform: analog_threshold
    id: ${ch6_cover_name}_opened
    sensor_id: ${ch6_cover_name}_current
    threshold: ${opened_current}
    internal: true
    filters:
      - delayed_on: 100ms
      
  - platform: analog_threshold
    id: ${ch7_cover_name}_opened
    sensor_id: ${ch7_cover_name}_current
    threshold: ${opened_current}
    internal: true
    filters:
      - delayed_on: 100ms
      
  - platform: analog_threshold
    id: ${ch8_cover_name}_opened
    sensor_id: ${ch8_cover_name}_current
    threshold: ${opened_current}
    internal: true
    filters:
      - delayed_on: 100ms