esphome:
  name: ${name}

  project:
    name: "nliaudat.floor-heating-controller"
    version: "1.94.dev"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino #esp-idf  not ready missing json and async_tcp
    version: recommended #latest
#    sdkconfig_options:
#      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

preferences:
  flash_write_interval: 60min
  
# Enable logging
logger:
  level: ERROR #NONE# ERROR #INFO #DEBUG  #VERBOSE
  baud_rate: 0 #to disable logging via UART
  logs:
    ads1115: ERROR
    adc: ERROR
    sensor: ERROR
    binary_sensor: ERROR
    cover: ERROR
    switch: ERROR
    climate: ERROR
    endstop : ERROR
    text_sensor : ERROR
    homeassistant.sensor: ERROR

# Enable Home Assistant API
api:
  reboot_timeout: 15min
      
ota:
    password: "12345678"    


# SN74HC595 I/O Expander (shift register) to control L9110s chips
sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: GPIO16 #Pin connected to SN74HC595 SER input
    clock_pin: GPIO5 #Pin connected to SN74HC595 SRCLK pin
    latch_pin: GPIO17 #Pin connected to SN74HC595 RCLK pin
    oe_pin: GPIO18 ### needed by esphome, but connected to GND (outputEnable is used only for pwm all th pin)
    sr_count: 2 #Number of daisy-chained shift registers, up-to 4  