esphome:
  name: ${name}

  project:
    name: "tecnologic.floor-heating-controller"
    version: "1.01"

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: arduino #esp-idf  not ready missing json and async_tcp
    version: latest
#    sdkconfig_options:
#      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

preferences:
  flash_write_interval: 60min
  
# Enable logging
logger:
  level: ERROR #NONE# ERROR #INFO #DEBUG  #VERBOSE
  baud_rate: 0 #to disable logging via UART
  logs:
    dallas: DEBUG
    ads1115: ERROR
    adc: ERROR
    sensor: ERROR
    binary_sensor: ERROR
    cover: ERROR
    output: ERROR
    switch: ERROR
    climate: ERROR
    endstop : ERROR
    text_sensor : ERROR

# Enable Home Assistant API
api:
  reboot_timeout: 15min
      
ota:
    password: "12345678"    
