climate:  
  - platform: pid
    id: ${ch1_thermostat_name}_thermostat
    name: ${ch1_thermostat_name}
    sensor: ${ch1_thermostat_sensor}
    default_target_temperature: ${ch1_default_target_temperature}
    heat_output: ${ch1_cover_name}_output_id
    #cool_output: ${ch1_cover_name}_output_id
    control_parameters:
      kp: ${pid_return_kp}
      ki: ${pid_return_ki}
      kd: 0
      min_integral: 0
      max_integral: ${integrator_limit}
    visual:
      min_temperature: 15 °C
      max_temperature: 25 °C
      temperature_step: 0.5 °C
      
  - platform: pid
    id: ${ch2_thermostat_name}_thermostat
    name: ${ch2_thermostat_name}
    sensor: ${ch2_thermostat_sensor}
    default_target_temperature: ${ch2_default_target_temperature}
    heat_output: ${ch2_cover_name}_output_id
    #cool_output: ${ch2_cover_name}_output_id
    control_parameters:
      kp: ${pid_return_kp}
      ki: ${pid_return_ki}
      kd: 0
      min_integral: 0
      max_integral: ${integrator_limit}
    visual:
      min_temperature: 15 °C
      max_temperature: 25 °C
      temperature_step: 0.5 °C

  - platform: pid
    id: ${ch3_thermostat_name}_thermostat
    name: ${ch3_thermostat_name}
    sensor: ${ch3_thermostat_sensor}
    default_target_temperature: ${ch3_default_target_temperature}
    heat_output: ${ch3_cover_name}_output_id
    #cool_output: ${ch3_cover_name}_output_id
    control_parameters:
      kp: ${pid_return_kp}
      ki: ${pid_return_ki}
      kd: 0
      min_integral: 0
      max_integral: ${integrator_limit}
    visual:
      min_temperature: 15 °C
      max_temperature: 25 °C
      temperature_step: 0.5 °C

  - platform: pid
    id: ${ch4_thermostat_name}_thermostat
    name: ${ch4_thermostat_name}
    sensor: ${ch4_thermostat_sensor}
    default_target_temperature: ${ch4_default_target_temperature}
    heat_output: ${ch4_cover_name}_output_id
    #cool_output: ${ch4_cover_name}_output_id
    control_parameters:
      kp: ${pid_return_kp}
      ki: ${pid_return_ki}
      kd: 0
      min_integral: 0
      max_integral: ${integrator_limit}
    visual:
      min_temperature: 15 °C
      max_temperature: 25 °C
      temperature_step: 0.5 °C

sensor:
  - platform: pid
    climate_id: ${ch1_thermostat_name}_thermostat
    name: ${ch1_cover_name} Result
    type: RESULT

  - platform: pid
    climate_id: ${ch2_thermostat_name}_thermostat
    name: ${ch2_cover_name} Result
    type: RESULT

  - platform: pid
    climate_id: ${ch3_thermostat_name}_thermostat
    name: ${ch3_cover_name} Result
    type: RESULT

  - platform: pid
    climate_id: ${ch4_thermostat_name}_thermostat
    name: ${ch4_cover_name} Result
    type: RESULT