cover:
  - platform: endstop
    name: ${ch1_cover_name}
    id: ${ch1_cover_name}_id
    device_class: damper
    open_duration: ${valve_open_time}
    open_endstop: valve_opened1
    open_action:
      - switch.turn_on: CH1_IB_pin
      - switch.turn_off: CH1_IA_pin

    close_duration: ${valve_close_time}
    close_endstop: valve_closed1
    close_action:
      - switch.turn_on: CH1_IA_pin
      - switch.turn_off: CH1_IB_pin

    stop_action:
      - switch.turn_off: CH1_IA_pin
      - switch.turn_off: CH1_IB_pin
    max_duration: ${valve_max_time}

  - platform: endstop
    name: ${ch2_cover_name}
    id: ${ch2_cover_name}_id
    device_class: damper
    open_duration: ${valve_open_time}
    open_endstop: valve_opened2
    open_action:
      - switch.turn_on: CH2_IB_pin
      - switch.turn_off: CH2_IA_pin

    close_duration: ${valve_close_time}
    close_endstop: valve_closed2
    close_action:
      - switch.turn_on: CH2_IA_pin
      - switch.turn_off: CH2_IB_pin

    stop_action:
      - switch.turn_off: CH2_IA_pin
      - switch.turn_off: CH2_IB_pin
    max_duration: ${valve_max_time}

  - platform: endstop
    name: ${ch3_cover_name}
    id: ${ch3_cover_name}_id
    device_class: damper
    open_duration: ${valve_open_time}
    open_endstop: valve_opened3
    open_action:
      - switch.turn_on: CH3_IB_pin
      - switch.turn_off: CH3_IA_pin

    close_duration: ${valve_close_time}
    close_endstop: valve_closed3
    close_action:
      - switch.turn_on: CH3_IA_pin
      - switch.turn_off: CH3_IB_pin

    stop_action:
      - switch.turn_off: CH3_IA_pin
      - switch.turn_off: CH3_IB_pin
    max_duration: ${valve_max_time}

  - platform: endstop
    name: ${ch4_cover_name}
    id: ${ch4_cover_name}_id
    device_class: damper
    open_duration: ${valve_open_time}
    open_endstop: valve_opened4
    open_action:
      - switch.turn_on: CH4_IB_pin
      - switch.turn_off: CH4_IA_pin

    close_duration: ${valve_close_time}
    close_endstop: valve_closed4
    close_action:
      - switch.turn_on: CH4_IA_pin
      - switch.turn_off: CH4_IB_pin

    stop_action:
      - switch.turn_off: CH4_IA_pin
      - switch.turn_off: CH4_IB_pin
    max_duration: ${valve_max_time}

# Example configuration entry
number:
  - platform: template
    id: ${ch1_cover_name}_override
    name: ${ch1_cover_name} Override
    initial_value: 0
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1

  - platform: template
    id: ${ch2_cover_name}_override
    name: ${ch2_cover_name} Override
    initial_value: 0
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1

  - platform: template
    id: ${ch3_cover_name}_override
    name: ${ch3_cover_name} Override
    initial_value: 0
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1

  - platform: template
    id: ${ch4_cover_name}_override
    name: ${ch4_cover_name} Override
    initial_value: 0
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1


# map the covers to float outputs
output:
  - platform: template
    id: ${ch1_cover_name}_output_id
    type: float
    write_action:
      - cover.control:
          id: ${ch1_cover_name}_id
          position: !lambda if(id(${ch1_thermostat_name}_thermostat).mode != CLIMATE_MODE_OFF) return state; else return id(${ch1_cover_name}_override).state / 100;
          

  - platform: template
    id: ${ch2_cover_name}_output_id
    type: float
    write_action:
      - cover.control:
          id: ${ch2_cover_name}_id
          position: !lambda if(id(${ch2_thermostat_name}_thermostat).mode != CLIMATE_MODE_OFF) return state; else return id(${ch2_cover_name}_override).state / 100;
          

  - platform: template
    id: ${ch3_cover_name}_output_id
    type: float
    write_action:
      - cover.control:
          id: ${ch3_cover_name}_id
          position: !lambda if(id(${ch3_thermostat_name}_thermostat).mode != CLIMATE_MODE_OFF) return state; else return id(${ch3_cover_name}_override).state / 100;
          

  - platform: template
    id: ${ch4_cover_name}_output_id
    type: float
    write_action:
      - cover.control:
          id: ${ch4_cover_name}_id
          position: !lambda if(id(${ch4_thermostat_name}_thermostat).mode != CLIMATE_MODE_OFF) return state; else return id(${ch4_cover_name}_override).state / 100;
          
sensor:
  - platform: template
    id: ${ch1_cover_name}_position_id
    name: ${ch1_cover_name} Position
    unit_of_measurement: '%'
    lambda: |-
        return id(${ch1_cover_name}_id).position * 100; 
    update_interval: 10s

  - platform: template
    id: ${ch2_cover_name}_position_id
    name: ${ch2_cover_name} Position
    unit_of_measurement: '%'
    lambda: |-
        return id(${ch2_cover_name}_id).position * 100; 
    update_interval: 10s

  - platform: template
    id: ${ch3_cover_name}_position_id
    name: ${ch3_cover_name} Position
    unit_of_measurement: '%'
    lambda: |-
        return id(${ch3_cover_name}_id).position * 100; 
    update_interval: 10s

  - platform: template
    id: ${ch4_cover_name}_position_id
    name: ${ch4_cover_name} Position
    unit_of_measurement: '%'
    lambda: |-
        return id(${ch4_cover_name}_id).position * 100; 
    update_interval: 10s
