dallas:
  - pin: 23


sensor:
  - platform: dallas
    #address: 0x1c0000031edd2a28
    index: 0
    name: "Flur Rücklauf Temperatur"
    id: "flur_return_temperature_sensor"
    
  - platform: dallas
    #address: 0x1c0000031edd2a28
    index: 1
    name: "Gäste WC Rücklauf Temperatur"
    id: "wc_eg_return_temperature_sensor"    

  - platform: dallas
    #address: 0x1c0000031edd2a28
    index: 2
    name: "WoZi 1 Rücklauf Temperatur"
    id: "wozi1_return_temperature_sensor"    

  - platform: dallas
    #address: 0x1c0000031edd2a28
    index: 3
    name: "WoZi 2 Rücklauf Temperatur"
    id: "wozi2_return_temperature_sensor" 
    
  - platform: dallas
    #address: 0x1c0000031edd2a28
    index: 4
    name: "Küche Rücklauf Temperatur"
    id: "kitchen_return_temperature_sensor"

  - platform: dallas
    #address: 0x1c0000031edd2a28
    index: 5
    name: "HWR Rücklauf Temperatur"
    id: "hwr_return_temperature_sensor"