
dallas:
  - pin: 15
    update_interval: "60s"

sensor:
  - platform: dallas
    address: 0x9ebc84231e64ff28
    name: "Room 1 temperature"
    id: "room_1_temperature_sensor"
    
  - platform: dallas
    address: 0x4d3c01f096631522
    name: "Room 2 temperature"
    id: "room_2_temperature_sensor"
  
  - platform: dallas
    address: 0x4d3c01f096631523
    name: "Room 3 temperature"
    id: "room_3_temperature_sensor"
  
  - platform: dallas
    address: 0x4d3c01f096631524
    name: "Room 4 temperature"
    id: "room_4_temperature_sensor"
    
  - platform: dallas
    address: 0x4d3c01f096631525
    name: "Room 5 temperature"
    id: "room_5_temperature_sensor"
  
  - platform: dallas
    address: 0x4d3c01f096631526
    name: "Room 6 temperature"
    id: "room_6_temperature_sensor"

  - platform: dallas
    address: 0x4d3c01f096631527
    name: "Room 7 temperature"
    id: "room_7_temperature_sensor"

  - platform: dallas
    address: 0x4d3c01f096631528
    name: "Room 8 temperature"
    id: "room_8_temperature_sensor"
    