
dallas:
  - pin: 23
    update_interval: "60s"

sensor:
  - platform: dallas
    address: 0x4d3c01f096631528 # bad
    name: "Bad R端cklauf Temperatur"
    id: "bad_return_temperature_sensor"
    
  - platform: dallas
    address: 0x113c01f096208828 
    name: "Tessa R端cklauf Temperatur"
    id: "tessa_return_temperature_sensor"    
  
  - platform: dallas
    address: 0xb03c01f0962a7a28
    name: "Kilian R端cklauf Temperatur"
    id: "kilian_return_temperature_sensor"    
  
  - platform: dallas
    address: 0x113c01f096100a28 # flur
    name: "Flur OG R端cklauf Temperatur"
    id: "flur_og_return_temperature_sensor" 
  
  - platform: dallas
    address: 0x403c01f096080428
    name: "Tessa Raum Temperatur "
    id: "tessa_room_temperature_sensor"
      
  - platform: dallas
    address: 0xfb062017e9e54228
    name: "Flur OG Raum Temperatur "
    id: "flur_og_room_temperature_sensor"
  
  - platform: dallas
    address: 0x790121113d299628
    name: "Bad Raum Temperatur "
    id: "bad_room_temperature_sensor"

  - platform: dallas
    address: 0x2001211135154928
    name: "Kilian Raum Temperatur "
    id: "kilian_room_temperature_sensor"
