i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: true

ads1115:
  - address: 0x48
    id: "ads1"

sensor:
  - platform: ads1115
    ads1115_id: "ads1"
    multiplexer: "A0_GND"
    gain: 0.256
    name: "Current Valve 1"
    id: "ads_current1"
    device_class: current
    update_interval: 20ms
    unit_of_measurement: "A"
    filters:
      - offset: 0.0
      - multiply: 1.070
      - sliding_window_moving_average:
          window_size: 30
          send_every: 10

  - platform: ads1115
    ads1115_id: "ads1"
    multiplexer: "A1_GND"
    gain: 0.256
    name: "Current Valve 2"
    id: "ads_current2"
    device_class: current
    update_interval: 20ms
    unit_of_measurement: "A"
    filters:
      - offset: 0.0
      - multiply: 1.070
      - sliding_window_moving_average:
          window_size: 30
          send_every: 10

  - platform: ads1115
    ads1115_id: "ads1"
    multiplexer: "A2_GND"
    gain: 0.256
    name: "Current Valve 3"
    id: "ads_current3"
    device_class: current
    update_interval: 20ms
    unit_of_measurement: "A"
    filters:
      - offset: 0.0
      - multiply: 1.070
      - sliding_window_moving_average:
          window_size: 30
          send_every: 10
  
  - platform: ads1115
    ads1115_id: "ads1"
    multiplexer: "A3_GND"
    gain: 0.256
    name: "Current Valve 4"
    id: "ads_current4"
    device_class: current
    update_interval: 20ms
    unit_of_measurement: "A"
    filters:
      - offset: 0.0
      - multiply: 1.070
      - sliding_window_moving_average:
          window_size: 30
          send_every: 10


