dallas:
  - pin: 23
    update_interval: "10s"

sensor:
  - platform: dallas
    address: 0xe93c01f096575828
    name: "Flur Rücklauf Temperatur"
    id: "flur_return_temperature_sensor"
    
  - platform: dallas
    address: 0xb23c01f0961bf228
    name: "Gäste WC Rücklauf Temperatur"
    id: "wc_eg_return_temperature_sensor"    
  
  - platform: dallas
    address: 0xc23c01f096852a28
    name: "WoZi 1 Rücklauf Temperatur"
    id: "wozi1_return_temperature_sensor"    
  
  - platform: dallas
    address: 0x383c01f096148e28
    name: "WoZi 2 Rücklauf Temperatur"
    id: "wozi2_return_temperature_sensor" 
    
  - platform: dallas
    address: 0xdd3c01f096519928
    name: "Küche Rücklauf Temperatur"
    id: "kitchen_return_temperature_sensor"
  
  - platform: dallas
    address: 0x5e3c01f0963a5528
    name: "Vorlauf Temperatur"
    id: "heat_temperature_sensor"
  