sensor:
  - platform: adc
    pin: GPIO1
    accuracy_decimals: 1
    attenuation: 11dB
    name: ${ch1_cover_name} Current
    id: "ads_current1"
    device_class: current
    update_interval: 2ms
    unit_of_measurement: "mA"
    filters:
      - offset: -1.25
      - multiply: 70
      - sliding_window_moving_average:
          window_size: 30
          send_every: 5

  - platform: adc
    pin: GPIO2
    accuracy_decimals: 1
    attenuation: 11dB
    name: ${ch2_cover_name} Current
    id: "ads_current2"
    device_class: current
    update_interval: 2ms
    unit_of_measurement: "mA"
    filters:
      - offset: -1.25
      - multiply: 70
      - sliding_window_moving_average:
          window_size: 30
          send_every: 5

  - platform: adc
    pin: GPIO3
    accuracy_decimals: 1
    attenuation: 11dB
    name: ${ch3_cover_name} Current
    id: "ads_current3"
    device_class: current
    update_interval: 2ms
    unit_of_measurement: "mA"
    filters:
      - offset: -1.25
      - multiply: 70
      - sliding_window_moving_average:
          window_size: 30
          send_every: 5
  
  - platform: adc
    pin: GPIO4
    accuracy_decimals: 1
    attenuation: 11dB
    name: ${ch4_cover_name} Current
    id: "ads_current4"
    device_class: current
    update_interval: 2ms
    unit_of_measurement: "mA"
    filters:
      - offset: -1.25
      - multiply: 70
      - sliding_window_moving_average:
          window_size: 30
          send_every: 5


