
dallas:
  - pin: 23
    update_interval: "10s"

sensor:
  - platform: dallas
    address: 0x4d3c01f096631528 # bad
    name: "Bad R端cklauf Temperatur"
    id: "bad_return_temperature_sensor"
    
  - platform: dallas
    address: 0xb03c01f0962a7a28 # kind1
    name: "Kind 1 R端cklauf Temperatur"
    id: "kind1_return_temperature_sensor"    
  
  - platform: dallas
    address: 0x113c01f096208828 # kind2
    name: "Kind 2 R端cklauf Temperatur"
    id: "kind2_return_temperature_sensor"    
  
  - platform: dallas
    address: 0x113c01f096100a28 # flur
    name: "Flur OG R端cklauf Temperatur"
    id: "flur_og_return_temperature_sensor" 
  
  - platform: dallas
    address: 0x403c01f096080428
    name: "Tessa Raum Temperatur "
    id: "kid_1_room_temperature_sensor"
      
  - platform: dallas
    address: 0xfb062017e9e54228
    name: "Raum 1 Temperatur "
    id: "room_1_temperature_sensor"
  
  - platform: dallas
    address: 0x790121113d299628
    name: "Raum 2 Temperatur "
    id: "room_2_temperature_sensor"

  - platform: dallas
    address: 0x2001211135154928
    name: "Raum 3 Temperatur "
    id: "room_3_temperature_sensor"


  - platform: dallas
    address: 0x4d3c01f096631528
    name: "Raum 4 Temperatur "
    id: "room_4_temperature_sensor"
  