dallas:
  - pin: 23
    update_interval: "60s"

sensor:
  - platform: dallas
    address: 0x113c01f096208828
    name: "Bad R端cklauf Temperatur"
    id: "bad_return_temperature_sensor"
    
  - platform: dallas
    address: 0x4d3c01f096631528
    name: "Kind 1 R端cklauf Temperatur"
    id: "kind1_return_temperature_sensor"    
  
  - platform: dallas
    address: 0x113c01f096100a28
    name: "Kind 2 R端cklauf Temperatur"
    id: "kind2_return_temperature_sensor"    
  
  - platform: dallas
    address: 0xb03c01f0962a7a28
    name: "Flur OG R端cklauf Temperatur"
    id: "flur_og_return_temperature_sensor" 
  
  - platform: dallas
    address: 0x403c01f096080428
    name: "Vorlauf Temperatur OG"
    id: "heat_temperature_sensor"
  